# Generated by Django 5.2 on 2025-05-24 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Paper', 'Paper'), ('Chapter', 'Chapter'), ('Proposal', 'Proposal'), ('Thesis', 'Thesis'), ('Report', 'Report'), ('Other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='submissions/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending Review', 'Pending Review'), ('Approved', 'Approved'), ('Feedback Provided', 'Feedback Provided'), ('Rejected', 'Rejected')], default='Pending Review', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
