# Generated by Django 5.2 on 2025-06-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_assignment_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('UX/UI', 'UX/UI'), ('Architecture', 'Architecture'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Paper', 'Paper'), ('Book', 'Book'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
