# Generated by Django 5.2 on 2025-05-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_file',
            field=models.FileField(blank=True, null=True, upload_to='feedback/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
