# Generated by Django 5.2 on 2025-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_rename_title_project_name_remove_project_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('UX/UI', 'UX/UI'), ('Architecture', 'Architecture'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Testing', 'Testing'), ('Deployment', 'Deployment')], max_length=50, null=True),
        ),
    ]
