# Generated by Django 5.2 on 2025-04-29 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Bursaries', 'Bursaries'), ('Invoices', 'Invoices'), ('Fitness', 'Fitness'), ('Equipment', 'Equipment/Office Resources'), ('Travel', 'Travel')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('oracle_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='adminpanel.costcentre')),
            ],
        ),
    ]
