# Generated by Django 5.2 on 2025-06-01 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in-progress', 'In Progress'), ('on-hold', 'On Hold'), ('completed', 'Completed')], max_length=50)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='feedback_docs/')),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('office_location', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(default='Dr.', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Bursaries', 'Bursaries'), ('Invoices', 'Invoices'), ('Fitness', 'Fitness'), ('Equipment', 'Equipment/Office Resources'), ('Travel', 'Travel')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('oracle_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='adminpanel.costcentre')),
            ],
        ),
    ]
