# Generated by Django 5.2 on 2025-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('writing', 'Writing & Development'), ('submission', 'Journal Submission'), ('review', 'Peer Review'), ('production', 'In Production'), ('published', 'Published')], default='writing', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('lead_author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('total_chapters', models.PositiveIntegerField(default=1)),
                ('completed_chapters', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('editor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('platform_logo', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper')], max_length=20)),
                ('internal_external', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('lead_author', models.CharField(max_length=255)),
                ('co_authors', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('review', 'Internal Review'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('published', 'Published'), ('rejected', 'Rejected')], max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('manuscript', models.FileField(upload_to='manuscripts/')),
                ('target_journal', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Book', 'Book Templates'), ('Research', 'Research Papers'), ('Software', 'Software Development')], max_length=50)),
                ('file', models.FileField(upload_to='templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
