# Generated by Django 5.2 on 2025-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontent',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learningcontent',
            name='platform_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
